apiVersion: v1
kind: Service
metadata:
  name: va-analytics-svc
  namespace: video-analytics
  labels:
    app: video-analytics
    component: analytics-api
spec:
  type: ClusterIP
  selector:
    app: video-analytics
    component: analytics-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
