apiVersion: v1
kind: ConfigMap
metadata:
  name: video-analytics-config
  namespace: video-analytics
data:
  APP_ENV: "production"
  FRONTEND_BASE_URL: "/"
  API_UPLOAD_BASE_URL: "/api/upload"
  API_ANALYTICS_BASE_URL: "/api/analytics"
