apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-frontend
  namespace: video-analytics
  labels:
    app: video-analytics
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-analytics
      component: frontend
  template:
    metadata:
      labels:
        app: video-analytics
        component: frontend
    spec:
      serviceAccountName: app-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 101        # numeric non-root UID (nginx user)
        fsGroup: 101
      containers:
        - name: va-frontend
          image: 801867402650.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: video-analytics-config
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080

